# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-19 04:23
from __future__ import unicode_literals

import book.views
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RE', 'Removed'), ('AC', 'Active')], default='AC', max_length=5)),
                ('create_user_id', models.IntegerField(editable=False, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_user_id', models.IntegerField(editable=False, null=True)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=20)),
                ('version', models.CharField(blank=True, default='', max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('trans', models.CharField(max_length=20)),
                ('press', models.CharField(max_length=20)),
                ('ISBN', models.CharField(max_length=20)),
                ('total_page', models.IntegerField(default=200)),
                ('price', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('real_price', models.DecimalField(decimal_places=2, default=40.0, max_digits=10)),
                ('score', models.FloatField(default=4.0, editable=False)),
                ('shelf_floor', models.IntegerField(default=1)),
                ('book_status', models.CharField(choices=[('ON', 'ON Shelf'), ('OUT', 'Check Out'), ('RE', 'Returned'), ('LO', 'Lost')], default='ON', max_length=10)),
                ('series', models.CharField(blank=True, default='', max_length=20)),
                ('seres_number', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RE', 'Removed'), ('AC', 'Active')], default='AC', max_length=5)),
                ('create_user_id', models.IntegerField(editable=False, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_user_id', models.IntegerField(editable=False, null=True)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
                ('order_number', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RE', 'Removed'), ('AC', 'Active')], default='AC', max_length=5)),
                ('create_user_id', models.IntegerField(editable=False, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_user_id', models.IntegerField(editable=False, null=True)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('book_status', models.CharField(choices=[('ON', 'ON Shelf'), ('OUT', 'Check Out'), ('RE', 'Returned'), ('LO', 'Lost')], default='NO', max_length=10)),
                ('time', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('SC', 'Scan Code'), ('SH', 'Shift')], default='SC', max_length=5)),
                ('return_date', models.DateField(default=book.views.calc_return_date)),
                ('returned_date', models.DateTimeField(blank=True)),
                ('allow_shift', models.BooleanField(default=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='book.Book')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RE', 'Removed'), ('AC', 'Active')], default='AC', max_length=5)),
                ('create_user_id', models.IntegerField(editable=False, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_user_id', models.IntegerField(editable=False, null=True)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('score', models.FloatField(default=5.0)),
                ('content', models.TextField(max_length=500)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.CheckOut')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RE', 'Removed'), ('AC', 'Active')], default='AC', max_length=5)),
                ('create_user_id', models.IntegerField(editable=False, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_user_id', models.IntegerField(editable=False, null=True)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('content', models.TextField(max_length=100)),
                ('wx_form_id', models.CharField(editable=False, max_length=100, null=True)),
                ('reply', models.TextField(blank=True, max_length=200)),
                ('reply_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RE', 'Removed'), ('AC', 'Active')], default='AC', max_length=5)),
                ('create_user_id', models.IntegerField(editable=False, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_user_id', models.IntegerField(editable=False, null=True)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('page', models.FloatField(default=1)),
                ('content', models.TextField(max_length=500)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.CheckOut')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RE', 'Removed'), ('AC', 'Active')], default='AC', max_length=5)),
                ('create_user_id', models.IntegerField(editable=False, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_user_id', models.IntegerField(editable=False, null=True)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('days', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_no', models.CharField(blank=True, max_length=50)),
                ('trade_no', models.CharField(blank=True, max_length=50)),
                ('pay_status', models.IntegerField(choices=[(-2, 'Failed'), (0, 'Paying'), (2, 'Success')], default=0)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.CheckOut')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RE', 'Removed'), ('AC', 'Active')], default='AC', max_length=5)),
                ('create_user_id', models.IntegerField(editable=False, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_user_id', models.IntegerField(editable=False, null=True)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('code', models.CharField(max_length=100)),
                ('location', models.CharField(default='', max_length=20)),
                ('floors', models.IntegerField(default=4)),
                ('capacity', models.IntegerField(default=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='book.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RE', 'Removed'), ('AC', 'Active')], default='AC', max_length=5)),
                ('create_user_id', models.IntegerField(editable=False, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_user_id', models.IntegerField(editable=False, null=True)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reason', models.TextField(max_length=100)),
                ('agreed', models.BooleanField(default=False)),
                ('reply', models.TextField(blank=True, max_length=100)),
                ('shift_status', models.CharField(choices=[('Req', 'Requested'), ('Arg', 'Agreed'), ('Com', 'Completed'), ('Abr', 'Abort'), ('Ref', 'Refused')], default='Req', max_length=3)),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('reply_time', models.DateTimeField(blank=True, null=True)),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
                ('checkout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='book.CheckOut')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RE', 'Removed'), ('AC', 'Active')], default='AC', max_length=5)),
                ('create_user_id', models.IntegerField(editable=False, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('update_user_id', models.IntegerField(editable=False, null=True)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('mobile', models.CharField(blank=True, default='', max_length=11)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('birth', models.DateField(blank=True)),
                ('job', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=book.views.calc_end_time)),
                ('wx_id', models.CharField(default='', editable=False, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='request_user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='book.UserProfile'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='book.UserProfile'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.UserProfile'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='book.Category'),
        ),
        migrations.AddField(
            model_name='book',
            name='shelf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='book.Shelf'),
        ),
    ]
